### ISSUE TITLE
feature request: display list of packages

### ISSUE THREAD

**Issue by crutchcorn** [ramsaylanier/module-docs#10]
I think it could be neat to display a virtual-scrolled list of level-0 (on package.json) dependancies and dev-dependancies of a project (with some form of seperator between them) as the main view with a message telling users they can `search` for any other library outside of that list at the bottom. I think this would make the UI more clear and useful at default

I can take on development of this, as I don't think it would be a huge amount of work, just wanted to run the idea past the repo first

**Comment by ramsaylanier** [comment]
I wonder if there is a way to integrate this with favorites somehow? Like show the list of package.json packages below the favorites? I like the idea

**Comment by ramsaylanier** [comment]
@crutchcorn merged in #12 which should address this feature.

**Comment by crutchcorn** [comment]
Sounds good. Sorry for delayed replies, father is in ICU
